default_region = "lancong"

[[regions]]
id = "lancong"
name_zh = "南昌"
status = "active"
path = "regions/lancong/region.toml"

[[regions]]
id = "fenni"
name_zh = "分宜"
status = "active"
path = "regions/fenni/region.toml"

[[regions]]
id = "fungcen"
name_zh = "丰城"
status = "active"
path = "regions/fungcen/region.toml"

[[regions]]
id = "tiqien"
name_zh = "黎川"
status = "active"
path = "regions/tiqien/region.toml"

[[regions]]
id = "xinyu"
name_zh = "新余市"
status = "active"
path = "regions/xinyu/region.toml"

[[regions]]
id = "songau"
name_zh = "上高"
status = "active"
path = "regions/songau/region.toml"
