default_region = "lancong"

[[regions]]
id = "lancong"
name_zh = "南昌"
status = "active"
path = "regions/lancong/region.toml"

[[regions]]
id = "fenni"
name_zh = "分宜"
status = "active"
path = "regions/fenni/region.toml"

[[regions]]
id = "fungcen"
name_zh = "丰城"
status = "active"
path = "regions/fungcen/region.toml"

[[regions]]
id = "tiqien"
name_zh = "黎川"
status = "active"
path = "regions/tiqien/region.toml"

[[regions]]
id = "sinyi"
name_zh = "新余市"
status = "active"
path = "regions/sinyi/region.toml"

[[regions]]
id = "songau"
name_zh = "上高"
status = "active"
path = "regions/songau/region.toml"

[[regions]]
id = "seusong"
name_zh = "宿松"
status = "active"
path = "regions/seusong/region.toml"

[[regions]]
id = "jingon"
name_zh = "吉安市"
status = "active"
path = "regions/jingon/region.toml"

[[regions]]
id = "yikyan-henfeng"
name_zh = "弋阳-横峰"
status = "active"
path = "regions/yikyan-henfeng/region.toml"

[[regions]]
id = "jisuibaedu"
name_zh = "吉水八都"
status = "active"
path = "regions/jisuibaedu/region.toml"

[[regions]]
id = "xyucuenn"
name_zh = "遂川"
status = "active"
path = "regions/xyucuenn/region.toml"
