[region]
id = "yikyan-henfeng"
name_zh = "弋阳-横峰"
status = "active"

[tone_classes]
1 = { name = "阴平", value = "44" }
2 = { name = "阳平", value = "22" }
3 = { name = "上声", value = "412" }
4 = { name = "阴去", value = "45" }
5 = { name = "阳去", value = "212" }
6 = { name = "阴入", value = "5" }
7 = { name = "阳入", value = "4" }

[ipa_tone_map]
0 = 0
1 = 1
2 = 2
3 = 3
5 = 4
6 = 5
7 = 6
8 = 7

[ipa_initial_map]
"f" = "f"
"k" = "g"
"kʰ" = "k"
"l" = "l"
"m" = "m"
"n" = "n"
"p" = "b"
"pʰ" = "p"
"s" = "s"
"t" = "d"
"ts" = "z"
"tsʰ" = "c"
"tɕ" = "j"
"tɕʰ" = "q"
"tʃ" = "j"
"tʃʰ" = "q"
"tʰ" = "t"
"x" = "h"
"ŋ" = "ng"
"ȵ" = "n"
"ɕ" = "x"
"ʃ" = "x"

[ipa_final_map]
"ɯ" = "e"
"ən" = "eng"
"ɤʔ" = "ek"
"uɤʔ" = "uek"
"yɛŋ" = "yuên"
"a" = "a"
"ai" = "ai"
"an" = "an"
"au" = "au"
"aʔ" = "ak"
"ei" = "êi"
"en" = "ên"
"i" = "i"
"ian" = "ian"
"iau" = "iau"
"iaʔ" = "iak"
"ien" = "iên"
"iəu" = "ieu"
"iɛ" = "iê"
"iɛn" = "iên"
"iɛʔ" = "iêk"
"iɪʔ" = "iek"
"m̩" = "m"
"n̩" = "n"
"o" = "o"
"u" = "u"
"ua" = "ua"
"uai" = "uai"
"uan" = "uan"
"uaʔ" = "uak"
"uei" = "uêi"
"uen" = "uên"
"uo" = "uo"
"uɔŋ" = "uong"
"uɔʔ" = "uok"
"uəʔ" = "uek"
"uɛ" = "uê"
"uɛn" = "uên"
"uɛʔ" = "uêk"
"uɪʔ" = "uek"
"y" = "yu"
"yaʔ" = "yuak"
"yn" = "yun"
"yŋ" = "yng"
"yɔŋ" = "yuong"
"yɔʔ" = "yuok"
"yəʔ" = "yuek"
"yɛ" = "yuê"
"yɛn" = "yuên"
"yɛʔ" = "yuêk"
"yɪʔ" = "yuek"
"ŋ̍" = "ng"
"ɔŋ" = "ong"
"ɔʔ" = "ok"
"ə" = "e"
"əu" = "eu"
"əŋ" = "eng"
"ɛ" = "ê"
"ɛen" = "ên"
"ɛn" = "ên"
"ɛʔ" = "êk"
"ɪʔ" = "ek"
"ɿ" = "ï"

[phonology]
syllables = "phonology/syllables.jsonl"
fuzzy_map = "../../fuzzy_scheme.tsv"
entering_codas = ["k"]

[language]
chars = "dictionaries/chars.tsv"
words = "dictionaries/words.tsv"
gan_chars = "dictionaries/gan_chars.tsv"
gan_words = "dictionaries/gan_words.tsv"
